---
- name: Enable EPEL (required for some packages on RHEL-family distros)
  ansible.builtin.package:
    name: epel-release
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] != 'Fedora'
  tags:
    - packages
