---
- name: Install internal root CA cert (RedHat-family)
  ansible.builtin.copy:
    content: "{{ root_ca_cert }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ base_domain }}-root-ca.crt"
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['os_family'] == 'RedHat'
  notify: update ca trust (redhat)
  tags:
    - ca_trust

- name: Install internal root CA cert (Debian-family)
  ansible.builtin.copy:
    content: "{{ root_ca_cert }}"
    dest: "/usr/local/share/ca-certificates/{{ base_domain }}-root-ca.crt"
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['os_family'] == 'Debian'
  notify: update ca trust (debian)
  tags:
    - ca_trust
