---
- import_playbook: vm/provision_vms.yml
  tags: provision_vms
- import_playbook: system/onboarding.yml
  tags: onboarding
- import_playbook: system/baseline_packages.yml
  tags: baseline_packages
- import_playbook: network/firewall.yml
  tags: firewall
- import_playbook: network/management_network.yml
  tags: management_network
- import_playbook: system/update.yml
  tags: update
- import_playbook: apps/mail_server.yml
  tags: mail_server
- import_playbook: apps/freeipa.yml
  tags: freeipa
- import_playbook: apps/podman.yml
  tags: podman
- import_playbook: system/logging.yml
  tags: logging
- import_playbook: apps/mail.yml
  tags: mail
