FROM docker.io/library/alpine:3.20

RUN apk add --no-cache rsyslog \
    && addgroup -g 101 rsyslog \
    && adduser -D -H -u 101 -G rsyslog -s /sbin/nologin rsyslog

COPY data/rsyslog.conf /etc/rsyslog.conf

EXPOSE 1514/udp 1514/tcp

USER rsyslog

ENTRYPOINT ["rsyslogd", "-n", "-f", "/etc/rsyslog.conf"]
